In [70]:
import pandas as pd 
import ast 
from tabulate import tabulate

In [44]:
df = pd.read_csv("ted_talks_es.csv")
df.head()

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,native_lang,available_lang,comments,duration,topics,related_talks,url,description,transcript
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,"['alternative energy', 'cars', 'climate change...","{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
1,7,"David Pogue dice ""La Simplicidad Vende""",David Pogue,{0: 'David Pogue'},{0: ['technology columnist']},{0: 'David Pogue is the personal technology co...,1920803,2006-02-24,2006-06-27,TED2006,en,"['ar', 'bg', 'de', 'el', 'en', 'es', 'fa', 'fr...",124.0,1286,"['computers', 'entertainment', 'interface desi...","{1725: '10 top time-saving tech tips', 2274: '...",https://www.ted.com/talks/david_pogue_simplici...,"El columnista del New York Times, David Pogue,...","Hola contestadora automática, mi vieja amiga. ..."
2,53,Un recorrido por la renovación urbana de la ma...,Majora Carter,{0: 'Majora Carter'},{0: ['activist for environmental justice']},{0: 'Majora Carter redefined the field of envi...,2664029,2006-02-26,2006-06-27,TED2006,en,"['ar', 'bg', 'bn', 'ca', 'cs', 'de', 'en', 'es...",219.0,1116,"['MacArthur grant', 'activism', 'business', 'c...",{1041: '3 stories of local eco-entrepreneurshi...,https://www.ted.com/talks/majora_carter_greeni...,"En una charla altamente emotiva, la activista ...","Si están presentes aquí hoy, y estoy muy conte..."
3,66,Ken Robinson dice que las escuelas matan la cr...,Sir Ken Robinson,{0: 'Sir Ken Robinson'},"{0: ['author', 'educator']}","{0: ""Creativity expert Sir Ken Robinson challe...",65052534,2006-02-25,2006-06-27,TED2006,en,"['af', 'ar', 'az', 'be', 'bg', 'bn', 'ca', 'cs...",4931.0,1164,"['children', 'creativity', 'culture', 'dance',...","{865: 'Bring on the learning revolution!', 173...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson plantea de manera entretenida...,"Buenos días. ¿Cómo están? Ha sido increíble, ¿..."
4,92,Hans Rosling nos muestra las mejores estadísti...,Hans Rosling,{0: 'Hans Rosling'},{0: ['global health expert; data visionary']},"{0: 'In Hans Rosling’s hands, data sings. Glob...",14501766,2006-02-22,2006-06-27,TED2006,en,"['ar', 'az', 'bg', 'bn', 'bs', 'cs', 'da', 'de...",628.0,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...","{2056: ""Own your body's data"", 2296: 'A visual...",https://www.ted.com/talks/hans_rosling_the_bes...,Una manera única de presentar datos. Con la en...,"Hace unos 10 años, emprendí la tarea de enseña..."

In [45]:
##Es un string ,necesitmaos que sea una lista para usar explode
type(df.topics[0])

str

In [46]:
### Citar de donde saque para usar literal eval 
### https://stackoverflow.com/questions/1894269/how-to-convert-string-representation-of-list-to-a-list

In [48]:
##Transformamos de string a lista
df["topics"] = df.topics.apply(lambda x : ast.literal_eval(x))

In [56]:
df.topics

0       [alternative energy, cars, climate change, cul...
1       [computers, entertainment, interface design, m...
2       [MacArthur grant, activism, business, cities, ...
3       [children, creativity, culture, dance, educati...
4       [Africa, Asia, Google, demo, economics, global...
                              ...
3916    [life, society, immigration, humanity, self, p...
3917    [TED-Ed, education, animation, fashion, climat...
3918    [life, emotions, communication, stigma, psycho...
3919    [coronavirus, pandemic, epidemiology, virus, b...
3920    [TED-Ed, education, history, animation, intell...
Name: topics, Length: 3921, dtype: object

In [58]:
#Expande la lista y crea una fila por topico
explode  = df.explode("topics")
explode

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,native_lang,available_lang,comments,duration,topics,related_talks,url,description,transcript
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,alternative energy,"{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,cars,"{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,climate change,"{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,culture,"{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
0,1,Al Gore sobre cómo evitar la crisis climática,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523396,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,environment,"{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,Con el mismo humor y humanidad que irradió en ...,Muchas gracias Chris. Y es en verdad un gran h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3920,62782,La oscura historia de las pruebas de coeficien...,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307246,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,animation,{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,Ver la lección completa en https://ed.ted.com/...,"En 1905, los psicólogos Alfred Binet y Théodor..."
3920,62782,La oscura historia de las pruebas de coeficien...,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307246,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,intelligence,{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,Ver la lección completa en https://ed.ted.com/...,"En 1905, los psicólogos Alfred Binet y Théodor..."
3920,62782,La oscura historia de las pruebas de coeficien...,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307246,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,testing,{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,Ver la lección completa en https://ed.ted.com/...,"En 1905, los psicólogos Alfred Binet y Théodor..."
3920,62782,La oscura historia de las pruebas de coeficien...,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307246,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,psychology,{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,Ver la lección completa en https://ed.ted.com/...,"En 1905, los psicólogos Alfred Binet y Théodor..."
3920,62782,La oscura historia de las pruebas de coeficien...,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307246,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,brain,{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,Ver la lección completa en https://ed.ted.com/...,"En 1905, los psicólogos Alfred Binet y Théodor..."

In [102]:
#Los topicos que hay 
topicos = list(explode.topics.unique())
for x in topicos : 
    print(x)

alternative energy
cars
climate change
culture
environment
global issues
science
sustainability
technology
computers
entertainment
interface design
media
music
performance
simplicity
software
MacArthur grant
activism
business
cities
green
inequality
politics
pollution
children
creativity
dance
education
parenting
teaching
Africa
Asia
Google
demo
economics
health
statistics
global development
visualizations
math
Christianity
God
atheism
comedy
religion
storytelling
humor
architecture
collaboration
design
library
brain
cognitive science
consciousness
evolution
philosophy
happiness
leadership
motivation
philanthropy
TED Prize
film
peace
social change
art
movies
disease
ebola
disaster relief
invention
open-source
entrepreneur
violin
wunderkind
youth
live music
piano
engineering
industrial design
DNA
biology
nature
product design
science and art
wikipedia
communication
community
gender
love
psychology
relationships
theater
women
cosmos
physics
universe
astronomy
choice
consumerism
food
marketing
race
narcotics
decision-making
personal growth
potential
aging
biotech
future
health care
cancer
investment
microfinance
poverty
telecom
transportation
corruption
military
policy
exploration
sports
travel
NASA
aircraft
flight
rocket science
AIDS
medicine
photography
genetics
faith
illusion
history
robots
obesity
poetry
success
work
indigenous peoples
anthropology
language
war
evolutionary psychology
complexity
time
innovation
map
urban planning
United States
interview
performance art
materials
code
work-life balance
ants
biodiversity
insects
ecology
animals
primates
Brazil
animation
typography
graphic design
apes
intelligence
fish
global commons
oceans
biomechanics
online video
biomimicry
singer
guitar
vocals
cello
self
china
web
electricity
memory
spoken word
composing
natural disaster
energy
museums
water
AI
marine biology
microsoft
virtual reality
women in business
Buddhism
New York
death
terrorism
Moon
Planets
adventure
mining
space
meme
bioethics
HIV
gaming
literature
markets
prosthetics
books
Social Science
sociology
violence
human origins
humanity
paleontology
solar system
asteroid
drones
solar energy
illness
depression
mental health
suicide
emotions
mindfulness
law
Best of the Web
String theory
magic
compassion
empathy
writing
play
world cultures
South America
infrastructure
ancient world
bees
garden
plants
toy
telescopes
hack
heart health
public health
big bang
quantum physics
fungi
bacteria
microbiology
news
submarine
sex
society
dinosaurs
archaeology
beauty
plastic
Vaccines
conducting
family
trees
extraterrestrial life
astrobiology
personality
introvert
origami
dark matter
diversity
identity
nanoscale
television
geology
life
morality
presentation
crime
evil
prison
democracy
smell
charter for compassion
social media
Senses
Mars
fashion
Alzheimer's
3D printing
goal-setting
curiosity
programming
chemistry
shopping
body language
bionics
virus
fear
birds
wind energy
extreme sports
prediction
productivity
coral reefs
mind
TED Fellows
agriculture
natural resources
india
neuroscience
TEDx
money
state-building
Antarctica
Anthropocene
Europe
data
sight
journalism
Internet
government
Sun
men
advertising
sanitation
homelessness
weather
big problems
rivers
Slavery
trafficking
sexual violence
Egypt
feminism
TEDMED
Autism spectrum disorder
science fiction
botany
mission blue
friendship
nuclear weapons
oil
novel
iraq
surveillance
Islam
monkeys
Iran
Middle East
sound
PTSD
population
manufacturing
bullying
gender equality
trust
sleep
Foreign Policy
medical research
Surgery
protests
deextinction
disability
nuclear energy
driverless cars
crowdsourcing
Brand
speech
failure
security
pain
blindness
Gender spectrum
glacier
mobility
LGBT
public spaces
encryption
human body
nonviolence
pharmaceuticals
molecular biology
behavioral economics
physiology
medical imaging
pregnancy
synthetic biology
hearing
jazz
Nobel Prize
finance
criminal justice
justice system
algorithm
TEDYouth
guns
exercise
conservation
immigration
TED-Ed
privacy
microbes
machine learning
skateboarding
augmented reality
forensics
painting
pandemic
meditation
Syria
Transgender
student
blockchain
cryptocurrency
Debate
farming
cloud
TED Books
refugees
street art
TED en Español
addiction
CRISPR
vulnerability
capitalism
grammar
Audacious Project
resources
discovery
TEDNYC
urban
TED Residency
biosphere
epidemiology
funny
healthcare
cooperation
neurology
arts
opioids
Science (hard)
book
Latin America
exoskeleton
start-up
inclusion
gay
testing
robot
stigma
human rights
development
rap
Humanities
coronavirus
autism

In [106]:
topicos[:223]

['alternative energy',
 'cars',
 'climate change',
 'culture',
 'environment',
 'global issues',
 'science',
 'sustainability',
 'technology',
 'computers',
 'entertainment',
 'interface design',
 'media',
 'music',
 'performance',
 'simplicity',
 'software',
 'MacArthur grant',
 'activism',
 'business',
 'cities',
 'green',
 'inequality',
 'politics',
 'pollution',
 'children',
 'creativity',
 'dance',
 'education',
 'parenting',
 'teaching',
 'Africa',
 'Asia',
 'Google',
 'demo',
 'economics',
 'health',
 'statistics',
 'global development',
 'visualizations',
 'math',
 'Christianity',
 'God',
 'atheism',
 'comedy',
 'religion',
 'storytelling',
 'humor',
 'architecture',
 'collaboration',
 'design',
 'library',
 'brain',
 'cognitive science',
 'consciousness',
 'evolution',
 'philosophy',
 'happiness',
 'leadership',
 'motivation',
 'philanthropy',
 'TED Prize',
 'film',
 'peace',
 'social change',
 'art',
 'movies',
 'disease',
 'ebola',
 'disaster relief',
 'invention',
 'open-source',
 'entrepreneur',
 'violin',
 'wunderkind',
 'youth',
 'live music',
 'piano',
 'engineering',
 'industrial design',
 'DNA',
 'biology',
 'nature',
 'product design',
 'science and art',
 'wikipedia',
 'communication',
 'community',
 'gender',
 'love',
 'psychology',
 'relationships',
 'theater',
 'women',
 'cosmos',
 'physics',
 'universe',
 'astronomy',
 'choice',
 'consumerism',
 'food',
 'marketing',
 'race',
 'narcotics',
 'decision-making',
 'personal growth',
 'potential',
 'aging',
 'biotech',
 'future',
 'health care',
 'cancer',
 'investment',
 'microfinance',
 'poverty',
 'telecom',
 'transportation',
 'corruption',
 'military',
 'policy',
 'exploration',
 'sports',
 'travel',
 'NASA',
 'aircraft',
 'flight',
 'rocket science',
 'AIDS',
 'medicine',
 'photography',
 'genetics',
 'faith',
 'illusion',
 'history',
 'robots',
 'obesity',
 'poetry',
 'success',
 'work',
 'indigenous peoples',
 'anthropology',
 'language',
 'war',
 'evolutionary psychology',
 'complexity',
 'time',
 'innovation',
 'map',
 'urban planning',
 'United States',
 'interview',
 'performance art',
 'materials',
 'code',
 'work-life balance',
 'ants',
 'biodiversity',
 'insects',
 'ecology',
 'animals',
 'primates',
 'Brazil',
 'animation',
 'typography',
 'graphic design',
 'apes',
 'intelligence',
 'fish',
 'global commons',
 'oceans',
 'biomechanics',
 'online video',
 'biomimicry',
 'singer',
 'guitar',
 'vocals',
 'cello',
 'self',
 'china',
 'web',
 'electricity',
 'memory',
 'spoken word',
 'composing',
 'natural disaster',
 'energy',
 'museums',
 'water',
 'AI',
 'marine biology',
 'microsoft',
 'virtual reality',
 'women in business',
 'Buddhism',
 'New York',
 'death',
 'terrorism',
 'Moon',
 'Planets',
 'adventure',
 'mining',
 'space',
 'meme',
 'bioethics',
 'HIV',
 'gaming',
 'literature',
 'markets',
 'prosthetics',
 'books',
 'Social Science',
 'sociology',
 'violence',
 'human origins',
 'humanity',
 'paleontology',
 'solar system',
 'asteroid',
 'drones',
 'solar energy',
 'illness',
 'depression',
 'mental health']

In [108]:
#Necesitamos saber el tema que va a tratr y seleccionar aquellos temas que se relacionan